# Generated by Django 4.0.6 on 2022-12-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0004_alter_contactenquiry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default=1, upload_to='image/'),
        ),
    ]
