# Generated by Django 3.2.16 on 2022-12-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0007_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.CharField(default='realstate', max_length=100),
        ),
    ]
